### ISSUE TITLE
Weird title position

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#200]
I tracked down one of the things causing the title to look like this:

<img width="530" alt="Image" src="https://github.com/user-attachments/assets/5fc31938-b164-4a07-a169-0990986c3388" />

I see it when exporting a notebook to HTML. I found that Jupyter notebooks output this in the stylesheet:

```css


.lm-DockPanel-handle[data-orientation='vertical']:after {
  top: 50%;
  min-height: 8px;
  transform: translateY(-50%);
}

.lm-SplitPanel[data-orientation='vertical'] > .lm-SplitPanel-handle:after {
  top: 50%;
  min-height: 8px;
  transform: translateY(-50%);
}

```

When these two specs are removed, the title goes to the right place. So I think the title is getting a `translateY(-50%);` style added to it (maybe inherited through the canvas).

I guess we could override this by hard-coding `translateY(0);` into the title, but then users wouldn't be able to overwrite it.
